### PR TITLE
Add multilingual support for the official OpenLayers workshop

### PR DESCRIPTION
**Pull request by ThomasG77**
I've been through the workshop for French people at http://osgeo.asso.fr/foss4gfr-2016/programme.html

For this purpose, I've translated the workshop to French.
As gitbook does support multi-languages e.g http://toolchain.gitbook.com/languages.html, I've moved the English content to a `en` directory. I also added the French content in the `fr` directory.
For building the workshop, I've changed the task to "archive:en" and created the "archive:fr" task. My intent was to build workshop package per language.

On the official website workshop URL http://openlayers.org/workshop/, it should look like the following screen capture whereas on the package, things remains exactly the same as it's per language.
multi-language-ol3

It also means that previous URLs for English will be http://openlayers.org/workshop/en/* instead of http://openlayers.org/workshop/

If the principles seam OK for you, merge this PR. IMO, corrections to French translation should be addressed in another PR.

### CODE REVIEW

**Comment by ThomasG77** [comment]
It seems Travis will not be happy with archive:en https://github.com/openlayers/workshop/blob/master/.travis.yml
I also maybe need to create a different openlayers-workshop.zip. Athe moment, in my PR, it creates for English and French the same file and it may conflict for putting both in the releases files.

**Comment by bartvde** [comment]
thanks for your efforts @ThomasG77 
@marcjansen how did you guys create the Gernan version?

**Comment by marcjansen** [comment]
We didn't create a 'de' version, we held the workshop with the english variabt. But we possibly will provide a German version for upcoming events.

Thanks a lot for the work on this,@ThomasG77 !

**Comment by ThomasG77** [comment]
I tried to change both "archive" tasks

```
...
    "archive:en": "npm run build && cp src/en/README.md build/openlayers-workshop/en/ && cd build && rm -rf openlayers-workshop/gitbook openlayers-workshop/index.html openlayers-workshop/search_index.json && mv openlayers-workshop/en openlayers-workshop-en && rm -rf openlayers-workshop && zip -FSr ../openlayers-workshop-en.zip openlayers-workshop-en",
    "archive:fr": "npm run build && cp src/fr/README.md build/openlayers-workshop/fr/ && cd build && rm -rf openlayers-workshop/gitbook openlayers-workshop/index.html openlayers-workshop/search_index.json && mv openlayers-workshop/fr/ openlayers-workshop-fr && rm -rf openlayers-workshop && zip -FSr ../openlayers-workshop-fr.zip openlayers-workshop-fr",
...
```

Why? As stated previously, it's to create two zip.

Previously, a created zip was in `build` directory. My tests are creating these files at the root of `workshop` directory because the command `npm run build` at the beginning of both archive tasks drop all the build directory. If I want to upload the two resulting files, I want to avoid file deletion. I also enforce zip overwriting with `zip -FSr ...`.

Hence, I need to change `.travis.yml` with

```
...
before_deploy:
  - npm run archive:en && npm run archive:fr
deploy:
  provider: releases
  api_key:
    secure: ag2ObhNaZYbULIABDARbHyvqk9DChYg6j6HZUmocdfM4Go/MF/OckpR0VntiMKpv+eQ8vdmTyRWVcW4Y/B+AOkMs/fhRs4rYOLq7BXWyLLbcvNaXP+3n6HDB/RZBPcNCYdQUo+oDDOyk7W9vF5T3o4aKlXFRLQIVQgABrwEQC1I=
  file:
    - build/openlayers-workshop-en.zip
    - build/openlayers-workshop-fr.zip
  on:
    repo: openlayers/workshop
    tags: true
```

I also need to add to `.gitignore` file with
```
openlayers-workshop-en.zip
openlayers-workshop-fr.zip
```

My main concern is the the one liner for each language and the "hacky" way to manage the archive creation.

Any suggestion to simplify?
I was thinking about creating a file to embed the task and use environment variable(s) to avoid duplication because of language suffix e.g "en" or "fr" at the moment.

**Comment by ahocevar** [comment]
How are updates for the non-English version going to work? I hope we won't end up with abandoned language versions.

**Comment by ThomasG77** [comment]
> How are updates for the non-English version going to work? I hope we won't end up with abandoned language versions.

**First reaction about your question,**

We want exact translation or to adapt content for local case, e.g particular projection for instance?

Why this question first? To decide if we share or not code parts e.g samples and configuration files. It could be addressed also with automatic code duplication from English to target language.
At the moment, each language directory has it own life: translations + samples code

**For translation maintenance itself,**

With gitbook, you only use markdown. There is no tool like "Transifex" to manage sentences/string translation separately.

IMO, for this technical reason, the only way to avoid "abandoned language versions" is all about translation policy. We should state for translation the update date and the corresponding English version. We should also decide to not show outdated translations after n months (or n version differences) and inform translators about this policy.

**Comment by ahocevar** [comment]
This all sounds quite involved in terms of tech and process. Wouldn't it be easier to have separate forks or even repositories for different languages?

**Comment by ThomasG77** [comment]
Although this PR would go in the limbo, there are no really problem if we need to set different repositories per language.
FYI, before submitting this PR, my French workshop translation was a copy of the English repository without managing a new hierarchy for the langs e.g https://github.com/webgeodatavore/workshop/tree/fr-unmodified-content

IMO, a repository like workshop-fr would be good enough for French. The OpenLayers team could also give rights to translators for these newly created workshop repositories per language.

@ahocevar, Your proposition would lessened the pain for the main workshop repo maintainer(s). We should just have to reference the different workshop languages translations from http://openlayers.org/en/latest/doc/

**Comment by ThomasG77** [comment]
Any other opinions to share?
Any plan to discuss translations at a PSC meeting?

**Comment by bartvde** [comment]
Personally I am in favour of using the gitbook built-in multi language support, unless the burden is really too much. I'm not yet convinced it is too much. We can bring it up in a hangout for sure.

**Comment by ahocevar** [comment]
I'm by no means meaning to block this. If @bartvde, the de-facto maintainer of this repository, says that this pull request does not increase the maintenance burden, I'm all in favour of it. I just want to be sure that things don't get more complicated for those who contribute to the English workshop. That said, I don't think this needs a long discussion.

**Comment by bartvde** [comment]
I haven't looked at the details as yet to be honest. Will try and do that soon.

**Comment by marcjansen** [comment]
We have done multilingual workshops with gitbook and it was a pleasure. It is always a burden to keep everything up to date, regardless of the technical solution. I am :+1: for gotbook multilingual approach.

**Comment by marcjansen** [comment]
Ping @bartvde, did you have a look at this PR?

**Comment by bartvde** [comment]
Not as yet, thanks for the reminder @marcjansen I'll have a look at this week, hopefully today or tomorrow

**Comment by bartvde** [comment]
@ThomasG77 is there a way to share more of the resources between the languages (symbolic links?), such as the screenshots and the example js code? It's a shame we have to copy all those resources that are the same.

**Comment by ThomasG77** [comment]
If it was only for the website, using symlinks would work. We would only need to upgrade gitbook-cli package as it fetches gitbook@3.0, able to manage symlinks (tried before answering).

As we bundle workshop generated material per language e.g `openlayers-workshop-en.zip` and `openlayers-workshop-fr.zip`, symlinks are a drawback here. They are broken as it would need for instance `../en/basics/debugger.png` when using a symlink from `fr/basics/debugger.png`, not available when bundling. For bundling ease, we need separate resources for each lang. Otherwise, I need to change completely the build process for bundling when using symlinked resources.

It would also restrict us at translations level to use symlinks. To be clearer, I'm not sure I always want an exact translation for the workshop. I would prefer French examples for projections or use of local datasets instead of only worldwide ones. I suppose this requirements would be the same for other languages.

IMO, using symlinks should not be a blocker but I'm not the repo maintainer.

**Comment by bartvde** [comment]
Good points @ThomasG77 I think I'm okay with merging this as is then, any objections from other devs?

**Comment by bartvde** [comment]
Also just to confirm, I assume you are okay with being the maintainer of the French version of the workshop right?

**Comment by ThomasG77** [comment]
No problem to be the maintainer of the workshop French version

**Comment by ThomasG77** [comment]
Any news about merging this PR?

**Comment by bartvde** [comment]
Let's merge it!

**Comment by marcjansen** [comment]
I am experiencing some issues with this PR in now. I'll double check tomorrow.

**Pull request merged**
