### PR TITLE
Translate the workshop to portuguese 

### PR DESCRIPTION
**Pull request by ranophoenix**
Hi,

I've translated this very useful workshop to portuguese language. It would be a great pleasure for me to be a maintainer of this version and keep it up to date.

Best regards.

### CODE REVIEW

**Comment by bartvde** [comment]
thank you @ranophoenix

**Comment by bartvde** [comment]
@ranophoenix the only thing that seems missing is adding an entry for the archive: https://github.com/openlayers/workshop/blob/master/package.json#L24

**Comment by ranophoenix** [comment]
Fixed!

Thanks.

**Comment by bartvde** [comment]
Thank you for your contribution @ranophoenix and looking forward to you maintaining the workshop in Portuguese

**Comment by ranophoenix** [comment]
Great! I'm really happy. Thanks.

**Pull request merged**
