### PR TITLE
Update OpenLayers to v3.16.0

### LINKED ISSUE #47: Add analyzerChecks in jscomp_off
When we will update ol3 to version v3.15.0, `analyzerChecks`must be added to the closure-util config (in `jscomp_off`).

See #46

### PR DESCRIPTION
**Pull request by marcjansen**
This updates the wokshop to use OpenLayers v3.16.0. The only chapter that needed adjustment was the custom builds one.

I'll gladly rebase this if #50 gets merged beforehand.

Please review.

Fixes #47

### CODE REVIEW

**Comment by bartvde** [comment]
LGTM

**Comment by marcjansen** [comment]
Rebased, will merge once the check is green.

**Comment by bartvde** [comment]
thanks @marcjansen

**Comment by marcjansen** [comment]
Thanks for the review @bartvde

**Pull request merged**
