### PR TITLE
Add a Custom builds chapter

### PR DESCRIPTION
**Pull request by elemoine**
This PR adds a "Custom builds" chapter to the workshop. This chapter discusses custom builds and shows how to create a custom build for one of the examples.

### CODE REVIEW

**Comment by elemoine** [comment]
By the way, I've tested the build procedure both on Linux and Windows.

**Comment by tschaub** [comment]
Nice.  Please merge.

**Comment by elemoine** [comment]
Add `ol.style.Text` to the list of exports.

**Comment by elemoine** [comment]
Check the build size with fewer externs.

**Comment by elemoine** [comment]
The size of the custom build is 177KB uncompressed (versus 413KB for the full build) and 62KB gzip'ed (versus 132KB for the full build).

I get the exactly the same numbers if I remove the `bingmaps.js`, `esrijson.js`, `geojson.js`, `tilejson.js` and `topojson.js` externs files from the build configuration file. So the externs have no impact at all on the size of the generated build.

**Pull request merged**
