### PR TITLE
Correct section 'update openlayers dependency'

### PR DESCRIPTION
**Pull request by marcjansen**
Title says it all.

Once this is in, I will release `v3.16.0` (no rc) if no one disagrees.

### CODE REVIEW

**Comment by bartvde** [comment]
+1

**Comment by marcjansen** [comment]
@bartvde: here it is https://github.com/openlayers/workshop/releases/tag/v3.16.0 please test your heart out.

**Comment by bartvde** [comment]
I will, thanks for all your work @marcjansen

**Comment by tsauerwein** [comment]
Thanks for doing the release! I went through the workshop and the only problem I found was with the Bing API key (https://github.com/openlayers/workshop/issues/62).

**Pull request merged**
