### PR TITLE
Various cleanup to the workshop

### PR DESCRIPTION
**Pull request by marcjansen**
This includes the following commits:

* Use OpenLayers v3.17.1, ddd6922
  * self-explanatory
* Remove explicit dependency for image-captions, 66e8d82
  * one depency less in main `package.json`, the used version seems to depend on what is configured in `book.json`
* Remove the example build JSON, e9c0e20
  * No need to have this in the repository wher it only grows old. Users have all needed information to create a build.json in the workshop chapter
* Harmonize `archive:en`/`archive:fr` scripts, 74fd6e4
  * minor
* No need for actual ol.css file	, 0c3975c
  * This was probably checked in erroneously
* Update build concepts examples, f289aa7
  * The example threre should be valid
* Ignore ol.css while in dev-mode, ac982f9
  * When developn on the workshop, the repository would otherwise be dirty
* Backport effective changes from 7f41e2f to fr/, 89df57c
  * … and have a functioning build configuration
* Reference files ending in `…en` or `…fr`, e66342a
  * Since we have multiple languages, the files to download have changed (at least once this deployed)

Please review.

/cc @bartvde, @ahocevar

### CODE REVIEW

**Comment by bartvde** [comment]
thanks @marcjansen LGTM please merge

Will you do a tag / release as well of the workshop after this merge so we can see if everything still works? TIA

**Comment by marcjansen** [comment]
I can do that. will you test that one then?

**Comment by bartvde** [comment]
Sure I can test that one.

**Comment by marcjansen** [comment]
Ouch: #56

**Pull request merged**
