### PR TITLE
Fix minor wording issue

### PR DESCRIPTION
**Pull request by tsauerwein**
~~Closes https://github.com/openlayers/workshop/issues/62~~

### CODE REVIEW

**Comment by marcjansen** [comment]
Not sure we want this in the repo… @bartvde ?

**Comment by bartvde** [comment]
No I don't think we want a key in the repo, it was taken out in the past for a good reason

**Comment by bartvde** [comment]
The first part of this PR is still valid though

**Comment by marcjansen** [comment]
truey-true.

**Comment by marcjansen** [comment]
Once this is changed to only include the first part I am :+1:

**Comment by tsauerwein** [comment]
Merging the small wording fix.

**Pull request merged**
