### PR TITLE
Corrections to Vector Tile section

### PR DESCRIPTION
**Pull request by walkermatt**

### CODE REVIEW

**Comment by walkermatt** [comment]
@ahocevar thanks, @ThomasG77 and I are delivering the workshop at http://uk.osgeo.org/foss4guk2018/ next week 👍

**Comment by walkermatt** [comment]
@ahocevar Hi, would it be possible to create a new release/ update the version on the website prior to our workshop at FOSS4G UK Thu (8th Mar)?

**Comment by ahocevar** [comment]
@walkermatt I just published the latest version. It would be nice if you could update and test the workshop with OpenLayers v4.6.4 and ol-mapbox-style v2.10.1. If you submit  a pull request for that, I'll publish again.

**Comment by walkermatt** [comment]
@ahocevar thanks, I'll try and update and test over the next couple of days.

**Pull request merged**
